version: '3.8'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-shared-container
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: Test_DB
      MYSQL_USER: alex
      MYSQL_PASSWORD: garbuz
    ports:
      - "3307:3307"
    volumes:
      - C:\tmp\docker\mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
